close_when_open = true
theme = "purple"
theme_location = ["$HOME/.config/walker/themes/"]
hotreload_theme = true
force_keyboard_focus = true
timeout = 90

[search]
placeholder = "  Run anything..."

[list]
max_entries = 100
cycle = true

# --------------------------
# BUILTINS
# --------------------------

# Aplicativos (normal)
[builtins.applications]
placeholder = "  Apps..."
prioritize_new = false
context_aware = false
show_sub_when_single = false
history = true
icon = "󰀻"

# Calculadora embutida
[builtins.calc]
hidden = false
placeholder = "󰃬  Calc..."
auto_copy = true

# Comandos customizados (como o Raycast)
[builtins.custom_commands]
hidden = false
file = "$HOME/.config/walker/commands.toml"

# Busca web
[builtins.websearch]
hidden = false
engine = "https://www.google.com/search?q="
placeholder = "🌐  Search web..."

# Emojis
[builtins.emojis]
hidden = false

# Clipboard (histórico)
[builtins.clipboard]
hidden = false
max_entries = 20
