#!/usr/bin/env bash
# Generate themed configuration fragments from dots/theme/palette.toml.
# Prefer editing palette.toml and rerunning this script (or theme-reload).
set -euo pipefail
export LC_ALL=C

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PALETTE="$ROOT/palette.toml"
DOTS_DIR="$(cd "$ROOT/.." && pwd)"

trim() {
  local var="$*"
  # shellcheck disable=SC2001
  echo "$(echo "$var" | sed -e 's/^[[:space:]]\+//' -e 's/[[:space:]]\+$//')"
}

# Parse palette.toml to variables like colors_background, typography_monospace_stack, etc.
parse_palette() {
  awk '
  function ltrim(s) { sub(/^[ \t\r\n]+/, "", s); return s }
  function rtrim(s) { sub(/[ \t\r\n]+$/, "", s); return s }
  function trim(s)  { return rtrim(ltrim(s)) }
  /^\s*#/ { next }
  /^\s*$/ { next }
  /^\[/ {
      section = trim($0)
      gsub(/\[/, "", section)
      gsub(/\]/, "", section)
      gsub(/\./, "_", section)
      next
  }
  {
      line = $0
      if (line ~ /=/) {
          split(line, parts, "=")
          key = trim(parts[1])
          value = trim(substr(line, index(line, "=") + 1))
          gsub(/\./, "_", key)
          if (value ~ /^"/) {
              gsub(/^"/, "", value)
              gsub(/"$/, "", value)
          }
          printf "%s_%s=%s\n", section, key, value
      }
  }' "$PALETTE"
}

while IFS='=' read -r key raw_value; do
  printf -v "$key" '%s' "$raw_value"
done < <(parse_palette)

format_alpha() {
  local alpha="$1"
  printf "%.4f" "$alpha" | sed -E 's/0+$//; s/\.$//'
}

parse_color() {
  local value="$1"
  local lower="${value,,}"
  local r g b a hex

  if [[ "$lower" =~ ^rgba ]]; then
    local inner="${value#*(}"
    inner="${inner%)*}"
    IFS=',' read -r r g b a <<< "$inner"
    r="$(trim "$r")"
    g="$(trim "$g")"
    b="$(trim "$b")"
    a="$(trim "${a:-1}")"
    printf "%d %d %d %s\n" "$(printf "%.0f" "$r")" "$(printf "%.0f" "$g")" "$(printf "%.0f" "$b")" "$a"
    return
  fi

  if [[ "$lower" =~ ^rgb ]]; then
    local inner="${value#*(}"
    inner="${inner%)*}"
    IFS=',' read -r r g b <<< "$inner"
    r="$(trim "$r")"
    g="$(trim "$g")"
    b="$(trim "$b")"
    printf "%d %d %d 1\n" "$(printf "%.0f" "$r")" "$(printf "%.0f" "$g")" "$(printf "%.0f" "$b")"
    return
  fi

  if [[ "$value" == \#* ]]; then
    hex="${value#\#}"
    if [[ ${#hex} -eq 6 ]]; then
      r=$((16#${hex:0:2}))
      g=$((16#${hex:2:2}))
      b=$((16#${hex:4:2}))
      printf "%d %d %d 1\n" "$r" "$g" "$b"
      return
    elif [[ ${#hex} -eq 8 ]]; then
      r=$((16#${hex:0:2}))
      g=$((16#${hex:2:2}))
      b=$((16#${hex:4:2}))
      local a_hex=$((16#${hex:6:2}))
      local alpha
      alpha=$(awk -v n="$a_hex" 'BEGIN{printf "%.4f", n/255}')
      printf "%d %d %d %s\n" "$r" "$g" "$b" "$alpha"
      return
    fi
  fi

  printf 'Unsupported color format: %s\n' "$value" >&2
  exit 1
}

to_css_rgba() {
  local value="$1"
  local override="${2:-}"
  local parsed
  parsed=($(parse_color "$value"))
  local r=${parsed[0]}
  local g=${parsed[1]}
  local b=${parsed[2]}
  local a=${parsed[3]}
  if [[ -n "$override" ]]; then
    a="$override"
  fi
  local alpha_fmt
  alpha_fmt=$(format_alpha "$a")
  printf "rgba(%d, %d, %d, %s)" "$r" "$g" "$b" "$alpha_fmt"
}

to_hex_rgba() {
  local value="$1"
  local override="${2:-}"
  local parsed
  parsed=($(parse_color "$value"))
  local r=${parsed[0]}
  local g=${parsed[1]}
  local b=${parsed[2]}
  local a=${parsed[3]}
  if [[ -n "$override" ]]; then
    a="$override"
  fi
  local alpha_byte
  alpha_byte=$(awk -v x="$a" 'BEGIN{printf "%d", (x*255)+0.5}')
  printf "#%02x%02x%02x%02x" "$r" "$g" "$b" "$alpha_byte"
}

to_hypr_rgba() {
  local hex
  hex="$(to_hex_rgba "$1" "${2:-}")"
  printf "rgba(%s)" "${hex#\#}"
}

first_font() {
  local stack="$1"
  local primary="${stack%%,*}"
  echo "$(trim "$primary")"
}

write_file() {
  local path="$1"
  local content="$2"
  printf '%s\n' "$content" > "$path"
}

# Derived values
shadow_css=$(to_css_rgba "$colors_shadow")
accent_css=$(to_css_rgba "$colors_accent")
accent_hypr=$(to_hypr_rgba "$colors_accent")
shadow_hypr=$(to_hypr_rgba "$colors_shadow")
walker_fg=$(to_css_rgba "$colors_foreground" "0.95")
walker_bg=$(to_css_rgba "$colors_background" "0.82")
walker_accent=$(to_css_rgba "$colors_accent" "0.35")
walker_border=$(to_css_rgba "$colors_border")
walker_shadow=$(to_css_rgba "$colors_shadow" "0.55")
button_radius=$(( metrics_border_radius * 3 ))
walker_box_radius=$(( metrics_border_radius * 2 ))
mako_border_radius=$(( metrics_border_radius + 2 ))
font_primary=$(first_font "$typography_monospace_stack")

# colors.css (GTK-compatible color definitions for Waybar)
write_file "$ROOT/colors.css" "$(cat <<EOF
/* Auto-generated by build_theme.sh — edit palette.toml instead. */
@define-color bg $(to_css_rgba "$colors_background_translucent");
@define-color bg_solid $colors_background;
@define-color surface $colors_surface;
@define-color fg $colors_foreground;
@define-color muted $colors_muted;
@define-color accent $colors_accent;
@define-color success $colors_success;
@define-color warning $colors_warning;
@define-color critical $colors_critical;
@define-color cursor $colors_cursor;
@define-color selection $colors_selection;
@define-color hover $(to_css_rgba "$colors_hover");
@define-color border $(to_css_rgba "$colors_border");
@define-color tooltip $colors_tooltip;
@define-color shadow $shadow_css;
EOF
)"

# Alacritty theme fragment
write_file "$ROOT/alacritty.toml" "$(cat <<EOF
# Auto-generated by build_theme.sh — edit palette.toml instead.
[colors.primary]
background = "$colors_background"
foreground = "$term_foreground"

[colors.cursor]
text = "$term_cursor_text"
cursor = "$colors_cursor"

[colors.selection]
text = "CellForeground"
background = "$colors_selection"

[colors.normal]
black = "$colors_background"
red = "$colors_critical"
green = "$colors_success"
yellow = "$colors_warning"
blue = "$colors_cursor"
magenta = "$colors_accent"
cyan = "$colors_selection"
white = "$colors_foreground"

[colors.bright]
black = "$colors_background"
red = "$colors_critical"
green = "$colors_success"
yellow = "$colors_warning"
blue = "$colors_cursor"
magenta = "$colors_accent"
cyan = "$colors_selection"
white = "#ffffff"
EOF
)"

# Hyprland palette fragment
write_file "$ROOT/hyprland.conf" "$(cat <<EOF
# Auto-generated by build_theme.sh — edit palette.toml instead.

general {
    col.active_border = $accent_hypr
    col.inactive_border = rgba(00000000)
}

decoration {
    rounding = ${metrics_window_radius}

    inactive_opacity = ${metrics_opacity_inactive}
    active_opacity = 1

    shadow {
        enabled = false
        range = 2
        render_power = 3
        color = $shadow_hypr
    }

    blur {
        enabled = true
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}
EOF
)"

# GTKLock style
write_file "$DOTS_DIR/gtklock/style.css" "$(cat <<EOF
/* Auto-generated by build_theme.sh — edit palette.toml instead. */
window {
  background: $(to_css_rgba "$colors_background_translucent");
}

#clock {
  font-family: $typography_monospace_stack;
  font-size: 48px;
  font-weight: 500;
  color: $colors_foreground;
}

#input {
  border-radius: ${metrics_border_radius}px;
  border: 1px solid $(to_css_rgba "$colors_accent" "0.3");
  background: $(to_css_rgba "$colors_background" "0.3");
  color: $colors_foreground;
  padding: 6px 10px;
}

#user {
  font-size: 12px;
  color: $colors_accent;
}

#prompt {
  font-size: 10px;
  color: $colors_muted;
}
EOF
)"

# Mako config
write_file "$DOTS_DIR/mako/config" "$(cat <<EOF
# Auto-generated by build_theme.sh — edit palette.toml instead.
font=$font_primary ${typography_code_size_small}
background-color=$(to_hex_rgba "$colors_background_translucent")
text-color=$(to_hex_rgba "$colors_foreground")
border-color=$(to_hex_rgba "$colors_accent")
border-size=2
border-radius=$mako_border_radius
padding=10
margin=10
width=350

anchor=top-right
max-visible=5
default-timeout=5000
ignore-timeout=0

output=*
icons=1
max-icon-size=64
layer=overlay

[urgency=low]
border-color=$(to_hex_rgba "$colors_success")

[urgency=normal]
border-color=$(to_hex_rgba "$colors_accent")

[urgency=high]
border-color=$(to_hex_rgba "$colors_critical")
default-timeout=10000
EOF
)"

# Wlogout style
write_file "$DOTS_DIR/wlogout/style.css" "$(cat <<EOF
/* Auto-generated by build_theme.sh — edit palette.toml instead. */
* {
  background-image: none;
  box-shadow: none;
}

window {
  background-color: $(to_css_rgba "$colors_background_translucent");
}

button {
  border-radius: $button_radius;
  border-color: $(to_css_rgba "$colors_border");
  text-decoration-color: $colors_foreground;
  color: $colors_foreground;
  background-color: $colors_surface;
  border-style: solid;
  border-width: 3px;
  background-repeat: no-repeat;
  background-position: center;
  background-size: 25%;
}

button:focus,
button:active,
button:hover {
  background-color: $(to_css_rgba "$colors_accent" "0.85");
  outline-style: none;
}

#lock {
  background-image: image(url("/usr/share/wlogout/icons/lock.png"), url("/usr/local/share/wlogout/icons/lock.png"));
}

#logout {
  background-image: image(url("/usr/share/wlogout/icons/logout.png"), url("/usr/local/share/wlogout/icons/logout.png"));
}

#suspend {
  background-image: image(url("/usr/share/wlogout/icons/suspend.png"), url("/usr/local/share/wlogout/icons/suspend.png"));
}

#hibernate {
  background-image: image(url("/usr/share/wlogout/icons/hibernate.png"), url("/usr/local/share/wlogout/icons/hibernate.png"));
}

#shutdown {
  background-image: image(url("/usr/share/wlogout/icons/shutdown.png"), url("/usr/local/share/wlogout/icons/shutdown.png"));
}

#reboot {
  background-image: image(url("/usr/share/wlogout/icons/reboot.png"), url("/usr/local/share/wlogout/icons/reboot.png"));
}
EOF
)"

# Walker style
write_file "$DOTS_DIR/walker/themes/purple/style.css" "$(cat <<EOF
/* Auto-generated by build_theme.sh — edit palette.toml instead. */
@define-color fg $walker_fg;
@define-color bg $walker_bg;
@define-color accent $walker_accent;
@define-color border $walker_border;

#window {
  color: @fg;
}

#box {
  border-radius: ${walker_box_radius}px;
  background: @bg;
  padding: 20px;
  border: 1px solid @border;
  box-shadow: 0 12px 28px $walker_shadow;
}

#search {
  background: transparent;
  padding: 8px;
  margin-bottom: 10px;
}

#prompt {
  margin-right: 10px;
  opacity: 0.4;
}

#input {
  background: none;
  color: @fg;
  font-size: 17px;
  border: none;
}

child {
  padding: 8px 12px;
  border-radius: ${metrics_border_radius}px;
}

child:hover,
child:selected {
  background: @accent;
  color: #fff;
}

#icon {
  margin-right: 8px;
}

#label {
  font-size: 15px;
  font-weight: 400;
}

#sub {
  opacity: 0.5;
  font-size: 0.85em;
}
EOF
)"
