[general]
live_config_reload = true

[window]
dynamic_padding = true
opacity = 1
blur = true
decorations_theme_variant = "Dark"

[font]
normal = { family =  "SF Mono", style = "regular" }
bold = { family =  "SF Mono", style = "bold" }
italic = { family =  "SF Mono", style = "italic" }
size = 9

[colors]
draw_bold_text_with_bright_colors = true
cursor = { text = "CellBackground" , cursor = "#a1a1a1" }

[colors.primary]
  background = "#000000"
  foreground = "#a2a2a2"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 200

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Middle", action = "Paste" },
]


[debug]
render_timer = false

